<?= $this->doctype(); ?>
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!--> <html lang="en" class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('Isis Dashboard '. $this->translate('novae'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', '')
        ->appendName('author', 'Mehdi Lefebvre')
    ?>
    <?= $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>
    <link href="/assets/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style-metro.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/style-responsive.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/css/themes/default.css" rel="stylesheet" type="text/css" id="style_color"/>
    <link href="/assets/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/gritter/css/jquery.gritter.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet" type="text/css" />
    <link href="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css"/>
    <link href="/assets/plugins/jqvmap/jqvmap/jqvmap.css" rel="stylesheet" type="text/css" media="screen"/>
    <link href="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.css" rel="stylesheet" type="text/css" media="screen"/>
    <link rel="shortcut icon" href="/favicon.ico" />
    <!-- TODO : include modernizr and cufon -->
</head>
<body class="page-header-fixed">
<div class="header navbar navbar-inverse navbar-fixed-top">
    <!-- BEGIN TOP NAVIGATION BAR -->
    <div class="navbar-inner">
        <div class="container-fluid">
            <!-- BEGIN LOGO -->
            <a class="brand" href="/">
                <img src="/assets/img/isis-dash-logo.png" alt="logo"/>
            </a>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse">
                <img src="/assets/img/menu-toggler.png" alt="" />
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            <ul class="nav pull-right">
                <?= $this->partial('widgets/notification_dropdown') ?>
                <?= $this->partial('widgets/inbox_dropdown') ?>
                <?= $this->partial('widgets/todo_dropdown') ?>
                <?= $this->partial('snippets/admin/user_login_dropdown') ?>
            </ul>
            <!-- END TOP NAVIGATION MENU -->
        </div>
    </div>
    <!-- END TOP NAVIGATION BAR -->
</div>
<!-- END HEADER -->
<!-- BEGIN CONTAINER -->
<div class="page-container">
    <?= $this->partial('snippets/admin/sidebars/default') ?>
    <!-- BEGIN PAGE -->
    <div class="page-content">
        <?= $this->partial('widgets/portlets/config') ?>
        <?= $this->content ?>
        <!-- BEGIN FOOTER -->
        <div class="footer">
            <div class="footer-inner">
                2013 &copy; Sis-direct
            </div>
            <div class="footer-tools">
			<span class="go-top">
			<i class="icon-angle-up"></i>
			</span>
            </div>
        </div>
        <?= $this->partial('snippets/modal/login') ?>
        <!-- END FOOTER -->
        <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
        <!-- BEGIN CORE PLUGINS -->
        <script src="/assets/plugins/jquery-1.10.1.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery-migrate-1.2.1.min.js" type="text/javascript"></script>
        <!-- IMPORTANT! Load jquery-ui-1.10.1.custom.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
        <script src="/assets/plugins/jquery-ui/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
        <!--[if lt IE 9]>
        <script src="/assets/plugins/excanvas.min.js"></script>
        <script src="/assets/plugins/respond.min.js"></script>
        <![endif]-->
        <script src="/assets/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery.blockui.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery.cookie.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/uniform/jquery.uniform.min.js" type="text/javascript" ></script>
        <!-- END CORE PLUGINS -->
        <!-- BEGIN PAGE LEVEL PLUGINS -->
        <script src="/assets/plugins/jqvmap/jqvmap/jquery.vmap.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.russia.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.world.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.europe.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.germany.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/maps/jquery.vmap.usa.js" type="text/javascript"></script>
        <script src="/assets/plugins/jqvmap/jqvmap/data/jquery.vmap.sampledata.js" type="text/javascript"></script>
        <script src="/assets/plugins/flot/jquery.flot.js" type="text/javascript"></script>
        <script src="/assets/plugins/flot/jquery.flot.resize.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery.pulsate.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/bootstrap-daterangepicker/date.js" type="text/javascript"></script>
        <script src="/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <script src="/assets/plugins/gritter/js/jquery.gritter.js" type="text/javascript"></script>
        <script src="/assets/plugins/fullcalendar/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery-easy-pie-chart/jquery.easy-pie-chart.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery.sparkline.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/jquery.idle.min.js" type="text/javascript"></script>
        <script src="/assets/plugins/bootbox/bootbox.js" type="text/javascript"></script>
        <script src="/assets/plugins/mustachejs/mustache.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL PLUGINS -->
        <!-- BEGIN PAGE LEVEL SCRIPTS -->
        <script src="/assets/scripts/app.js" type="text/javascript"></script>
        <script src="/assets/scripts/index.js" type="text/javascript"></script>
        <!-- END PAGE LEVEL SCRIPTS -->
        <script>
            var idleArmed = <?= (getenv('APPLICATION_ENV') == 'development' || false) ? 'true' : 'false' ?>;
            jQuery(document).ready(function() {
                var login_script_loaded = false;
                App.init(); // initlayout and core plugins
                Index.init();
                Index.initJQVMAP(); // init index page's custom scripts
                Index.initCalendar(); // init index page's custom scripts
                Index.initCharts(); // init index page's custom scripts
                Index.initChat();
                Index.initMiniCharts();
                Index.initDashboardDaterange();
                Index.initIntro();

                bootbox.setBtnClasses({
                    OK : 'green',
                    CONFIRM : 'green',
                    CANCEL : 'red'
                });

                if(idleArmed) {
                    $(document).idle({
                        onIdle: function(){
                            //bootbox.alert("Your no  longer logged in");
                            $("#loginModalForm").on('show', function() {
                                console.log('modal shown');
                                if(!login_script_loaded) {
                                    $.getScript('/assets/scripts/on_demand/login_modal.js');
                                    login_script_loaded = true;
                                }
                            }).modal();
                        },
                        idle: 5 * 60 * 1000
                    });
                }
            });
        </script>
        <!-- END JAVASCRIPTS -->
        <!--script type="text/javascript">  var _gaq = _gaq || [];  _gaq.push(['_setAccount', 'UA-37564768-1']);  _gaq.push(['_setDomainName', 'keenthemes.com']);  _gaq.push(['_setAllowLinker', true]);  _gaq.push(['_trackPageview']);  (function() {    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;    ga.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'stats.g.doubleclick.net/dc.js';    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);  })();</script-->
</body>
<!-- END BODY -->
</html>