<?php
$children = $this->viewModel()->getCurrent()->getChildren();
$container = $children[0];
?>
<form class="form-horizontal" action='#' method="POST">
    <div class="alert alert-info">You are no longer login, please fill in the form to continue to use the application</div>
    <fieldset>
        <div class="control-group">
            <!-- Username -->
            <label class="control-label" for="username">Username</label>
            <div class="controls">
                <input type="hidden" id="username" name="username" value="<?= $this->username ?>" placeholder="" class="input-xlarge">
                <span class="login-readonly"><?= $container->username ?></span>
            </div>
        </div>

        <div class="control-group">
            <!-- Password-->
            <label class="control-label" for="password">Password</label>
            <div class="controls">
                <input type="password" id="password" name="password" placeholder="" class="input-xlarge">
            </div>
        </div>


        <div class="control-group">
            <!-- Button -->
            <div class="controls">
                <button class="btn green btn-login">Login</button>
                <button class="btn red btn-disconnect">Disconnect</button>
            </div>
        </div>
    </fieldset>
</form>