<!-- BEGIN LOGIN -->
<div class="content">
    <!-- BEGIN LOGIN FORM -->
    <form class="form-vertical login-form" action="/administration/connection/login" method="post">
        <h3 class="form-title"><?= $this->translate('Login to your account') ?></h3>

        <div class="alert alert-error hide">
            <button class="close" data-dismiss="alert"></button>
            <span><?= $this->translate('Enter any username and password') ?>.</span>
        </div>
        <div class="control-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Username') ?></label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-user"></i>
                    <input class="m-wrap placeholder-no-fix" type="text" placeholder="Username" name="username" id="usernameLoginInput" />
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Password') ?></label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-lock"></i>
                    <input class="m-wrap placeholder-no-fix" type="password" placeholder="Password" name="password" id="passwordLoginInput" />
                </div>
            </div>
        </div>
        <div class="form-actions">
            <label class="checkbox">
                <input type="checkbox" name="remember" value="1"/> <?= $this->translate('Remember me') ?>
            </label>
            <button type="submit" class="btn green pull-right">
                <?= $this->translate('login') ?> <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
        <div class="forget-password">
            <h4><?= $this->translate('Forgot your password') ?> ?</h4>

            <p>
                <?= $this->translate('no worries') ?>, <?= $this->translate('click') ?> <a href="javascript:;" class="" id="forget-password"><?= $this->translate('here') ?></a>
                <?= $this->translate('to reset your password') ?>.
            </p>
        </div>
        <div class="create-account">
            <p>
                <?= $this->translate('Don\'t have an account yet') ?> ?&nbsp;
                <a href="javascript:;" id="register-btn" class=""><?= $this->translate('Create an account') ?></a>
            </p>
        </div>
    </form>
    <!-- END LOGIN FORM -->
    <!-- BEGIN FORGOT PASSWORD FORM -->
    <form class="form-vertical forget-form" action="http://www.keenthemes.com/preview/metronic/index.html">
        <h3 class=""><?= $this->translate('Forget Password') ?> ?</h3>

        <p><?= $this->translate('Enter your e-mail address below to reset your password') ?>.</p>

        <div class="control-group">
            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-envelope"></i>
                    <input class="m-wrap placeholder-no-fix" type="text" placeholder="Email" name="email"/>
                </div>
            </div>
        </div>
        <div class="form-actions">
            <button type="button" id="back-btn" class="btn">
                <i class="m-icon-swapleft"></i> <?= $this->translate('Back') ?>
            </button>
            <button type="submit" class="btn green pull-right">
                <?= $this->translate('Submit') ?> <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END FORGOT PASSWORD FORM -->
    <!-- BEGIN REGISTRATION FORM -->
    <form class="form-vertical register-form" action="http://www.keenthemes.com/preview/metronic/index.html">
        <h3 class=""><?= $this->translate('Sign Up') ?></h3>

        <p><?= $this->translate('Enter your account details below') ?>:</p>

        <div class="control-group">
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Username') ?></label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-user"></i>
                    <input class="m-wrap placeholder-no-fix" type="text" placeholder="<?= $this->translate('Username') ?>" name="username" id="username"/>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Password') ?></label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-lock"></i>
                    <input class="m-wrap placeholder-no-fix" type="password" id="register_password"
                           placeholder="<?= $this->translate('Password') ?>" name="password" id="password"/>
                </div>
            </div>
        </div>
        <div class="control-group">
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Re-type your password') ?>"</label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-ok"></i>
                    <input class="m-wrap placeholder-no-fix" type="password" placeholder="<?= $this->translate('Re-type your password') ?>"
                           name="rpassword" id="rpassword"/>
                </div>
            </div>
        </div>
        <div class="control-group">
            <!--ie8, ie9 does not support html5 placeholder, so we just show field title for that-->
            <label class="control-label visible-ie8 visible-ie9"><?= $this->translate('Email') ?></label>

            <div class="controls">
                <div class="input-icon left">
                    <i class="icon-envelope"></i>
                    <input class="m-wrap placeholder-no-fix" type="email" placeholder="<?= $this->translate('Email') ?>" name="email" id="email"/>
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox" name="tnc" id="tnc" /> <?= $this->translate('I agree to the') ?> <a href="#"><?= $this->translate('Terms of Service') ?></a> <?= $this->translate('and') ?> <a href="#">Privacy
                        <?= $this->translate('Policy') ?></a>
                </label>

                <div id="register_tnc_error"></div>
            </div>
        </div>
        <div class="form-actions">
            <button id="register-back-btn" type="button" class="btn">
                <i class="m-icon-swapleft"></i> <?= $this->translate('Back') ?>
            </button>
            <button type="submit" id="register-submit-btn" class="btn green pull-right">
                <?= $this->translate('Sign Up') ?> <i class="m-icon-swapright m-icon-white"></i>
            </button>
        </div>
    </form>
    <!-- END REGISTRATION FORM -->
</div>


<div data-keyboard="false" data-backdrop="static" tabindex="-1" class="modal hide fade" id="loginAlertForm" aria-hidden="true" style="width: 100%; margin-left: 0; left: 0;overflow: hidden">
    <div class="modal-body">
        <p>Would you like to continue with some arbitrary task?</p>
    </div>
    <div class="modal-footer">
        <button class="btn red btn-large" data-dismiss="modal" type="button">Ok</button>
    </div>
</div>